version: "3.8"  # You can adjust the version according to your needs

services:
  server:
    build: ./server  # Build the Docker image from the "server" directory
    container_name: python_server  # Name the container
    ports:
      - "5000:5000"  # Expose Flask on port 5000 externally and internally
    volumes:
      - ./server:/app  # Mount the entire server directory into the container
      - ./server/flask.db:/app/flask.db  # Mount the SQLite database file
    env_file:
      - ./server/.env