version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leafscan_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: zebbb/leafscan-app:latest
    depends_on:
      - db
    container_name: leafscan-app
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:admin123@db:5432/leafscan_db"
      SECRET_KEY: "secret_hehehehehehehehhehe"
      MAIL_SERVER: "smtp.googlemail.com"
      MAIL_PORT: 587
      MAIL_USERNAME: "leafscan.scanner@gmail.com"
      MAIL_PASSWORD: "tmmbsjkmobbrwctk"
      MAIL_USE_TLS: "True"
      MAIL_DEFAULT_SENDER: "leafscan.scanner@gmail.com"
    ports:
      - "5000:5000"

volumes:
  postgres_data:
