"""Create scan_records table

Revision ID: 0aeff2798666
Revises: 7c1a4a6b5384
Create Date: 2024-12-03 19:12:31.023663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeff2798666'
down_revision = '7c1a4a6b5384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_today', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('scanned_today')

    # ### end Alembic commands ###
