"""Create scan_records table

Revision ID: b8e022f6636f
Revises: 5919a2984f6b
Create Date: 2024-12-03 17:59:07.240340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e022f6636f'
down_revision = '5919a2984f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('more_info_url')
        batch_op.drop_column('cause')
        batch_op.drop_column('contributing_factors')
        batch_op.drop_column('prevention')
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('prevention', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contributing_factors', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cause', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('more_info_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
